### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by vaporrrr** [vaporrrr/Summit#11]
When selecting a school district on Login screen:
```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at VirtualizedList (http://localhost:19006/static/js/bundle.js:167976:34)
    at FlatList (http://localhost:19006/static/js/bundle.js:166052:34)
    at div
    at http://localhost:19006/static/js/bundle.js:155402:25
    at http://localhost:19006/static/js/bundle.js:150545:21
    at div
    at http://localhost:19006/static/js/bundle.js:155402:25
    at div
    at http://localhost:19006/static/js/bundle.js:155402:25
    at http://localhost:19006/static/js/bundle.js:149455:22
    at div
    at http://localhost:19006/static/js/bundle.js:155402:25
    at ModalFocusTrap (http://localhost:19006/static/js/bundle.js:149581:21)
    at div
```
This is due to [react-native-dropdown-picker](https://www.npmjs.com/package/react-native-dropdown-picker)

**Comment by vaporrrr** [comment]
https://github.com/facebook/react/blob/main/CHANGELOG.md#react-2
